"""Contrainte's evidence-first deterministic engineering core."""

from .assembly import Assembly, PartOccurrence, RigidTransform
from .axial import AxialCase, AxialResult, solve_axial_case
from .cad import PrismaticPart, ThroughHole, compile_part, verify_cad_bundle
from .component import (
    ArtifactRef,
    ComponentInterface,
    ComponentManifest,
    ExactInterfaceFrame,
)
from .component_assembly import (
    ComponentAssembly,
    ComponentBinding,
    ComponentPairClearance,
    SourceFileRef,
    compile_component_assembly,
    prepare_component_assembly,
    verify_component_assembly_bundle,
)
from .exact_transform import ExactRigidTransform, ExactRotation3, ExactVector3
from .interface_assembly import (
    InconclusiveReason,
    InterfaceAssembly,
    InterfaceAssemblyResult,
    InterfaceEndpoint,
    InterfaceEvidenceSummary,
    InterfaceMate,
    InterfaceOccurrence,
    InterfaceOccurrenceV2,
    MateAlternative,
    ParticipantEvidenceSummary,
    ParticipantKind,
    ProtectedReferenceParticipant,
    ReleasedComponentParticipant,
    SelectedMateAlternative,
    SolvedOccurrence,
    SolveStatus,
    solve_interface_assembly,
    verify_interface_assembly_result,
    verify_interface_assembly_solution,
)
from .materials import MaterialRecord
from .pipeline import compile_bundle, verify_bundle
from .program import DesignProgram, DesignTask, GoalContract
from .reference_component import (
    DesignAroundProjection,
    DesignAroundRequest,
    ReferenceComponentManifest,
    project_design_around,
    seal_design_around_request,
    seal_reference_component,
    verify_design_around_projection,
)
from .release import (
    ComponentReleaseRequest,
    derive_component_manifest,
    reproduce_local_component_shape,
)
from .sketch import (
    CircularHole,
    SketchConstraint,
    SketchExtrusion,
    SketchPoint,
    SketchProfile,
    compile_sketch_extrusion,
    solve_constraints,
    verify_sketch_bundle,
)
from .solid import SolidProgram
from .workspace import DesignWorkspace, ObjectRef

__all__ = [
    "ArtifactRef",
    "Assembly",
    "AxialCase",
    "AxialResult",
    "CircularHole",
    "ComponentAssembly",
    "ComponentBinding",
    "ComponentInterface",
    "ComponentManifest",
    "ComponentPairClearance",
    "ComponentReleaseRequest",
    "DesignAroundProjection",
    "DesignAroundRequest",
    "DesignProgram",
    "DesignTask",
    "DesignWorkspace",
    "ExactInterfaceFrame",
    "ExactRigidTransform",
    "ExactRotation3",
    "ExactVector3",
    "GoalContract",
    "InconclusiveReason",
    "InterfaceAssembly",
    "InterfaceAssemblyResult",
    "InterfaceEndpoint",
    "InterfaceEvidenceSummary",
    "InterfaceMate",
    "InterfaceOccurrence",
    "InterfaceOccurrenceV2",
    "MateAlternative",
    "MaterialRecord",
    "ObjectRef",
    "PartOccurrence",
    "ParticipantEvidenceSummary",
    "ParticipantKind",
    "PrismaticPart",
    "ProtectedReferenceParticipant",
    "ReferenceComponentManifest",
    "ReleasedComponentParticipant",
    "RigidTransform",
    "SelectedMateAlternative",
    "SketchConstraint",
    "SketchExtrusion",
    "SketchPoint",
    "SketchProfile",
    "SolidProgram",
    "SolveStatus",
    "SolvedOccurrence",
    "SourceFileRef",
    "ThroughHole",
    "compile_bundle",
    "compile_component_assembly",
    "compile_part",
    "compile_sketch_extrusion",
    "derive_component_manifest",
    "prepare_component_assembly",
    "project_design_around",
    "reproduce_local_component_shape",
    "seal_design_around_request",
    "seal_reference_component",
    "solve_axial_case",
    "solve_constraints",
    "solve_interface_assembly",
    "verify_bundle",
    "verify_cad_bundle",
    "verify_component_assembly_bundle",
    "verify_design_around_projection",
    "verify_interface_assembly_result",
    "verify_interface_assembly_solution",
    "verify_sketch_bundle",
]

__version__ = "0.1.0"
